### ISSUE TITLE
Should we have standards on pagination?

### ISSUE THREAD

**Issue by delauxs** [metocean/api-conventions#19] opened 2019-11-19 02:21 UTC
Following a discussion with @Ascendzor.
Apparently some APIs like obs API have pagination enabled and hence depending on the resolution of the dataset of interest either all or part of the requested data gets returned. In other cases, no pagination is enable and all the data is always returned.

Do we think we need a uniform behaviour across APIs with respect to pagination or do we just need to have API behaviour regarding to pagination documented in MDS?

**Comment by Ascendzor** [comment] 2019-11-19 03:11
The wider issue is how we resolve sharding requests, we might be after more data than one HTTP request can reliably resolve. I can see three solutions to this problem:
1) standardized Pagination
2) standardized timeResolution
3) Do nothing / let the agents figure it out

**Pagination**
Pros: Works for all datasets.
Cons: requires development for all existing and new endpoints.

**timeResolution**
Standardizing a timeResolution property on datasets. If we have a time range and a time resolution then we can know how many datapoints we will receive from a request. This will allow us to breakdown our request into shards before making any requests. However the problem is that it may not make sense for all datasets, some datasets like models could guarantee a timeResolution, some datasets like observations can give a best-guess, and some event-based datasets like lightning cannot give any estimation. So that complexity would need to be ironed out.

**Do nothing**
If the other two are too hard, we can accept the risks and carry on working on important things elsewhere. We do have an agent to have a first look at the datasets before the customer sees them.

**Comment by aportagain** [comment] 2019-11-26 23:25
Isn't option 1 pretty much what we were already discussing in https://github.com/metocean/api-conventions/issues/7 a while back?

**Comment by aportagain** [comment] 2020-09-28 21:37
I don't think 2 (standardised time resolution) will ever work well with observations, where instruments / datasets often have massive gaps in time, and sometimes even change expected time resolution / sampling interval (or we change the subsampling we do after obtaining the data).

**Comment by aportagain** [comment] 2020-09-28 21:37
I'm very much in favour of option 1 (pagination). I don't think we should require our APIs to provide this, but for those that do, we should agree on how they do it.

**Comment by aportagain** [comment] 2020-09-28 21:38
Sooo... I'd like to close this issue, in favour of #7 ... :) Is that OK @Ascendzor , @delauxs ?

**Comment by aportagain** [comment] 2020-09-28 23:16
@AndreLobato just FYI: closing in favour of #7 .

**Closed by aportagain** 2020-09-28 23:16 UTC
Labels: minor, new item
